version: '3.9'
services:
  plexcleaner:
    build: .
    container_name: plexcleaner
    env_file: .env  # Load environment variables
    volumes:
      - /Volumes/Multimedia/Video:/media
    restart: unless-stopped
